In [1]:
import pandas as pd
import numpy as np
from pandasql import sqldf
from collections import Counter

In [2]:
cloud = pd.read_csv("processed_data/prossed_cloud.csv", encoding='utf-8')
kuwo = pd.read_csv("processed_data/prossed_kuwo.csv", encoding='utf-8')

In [3]:
cloud

,playlist_id,playlist_name,song_id,song_name,artist_id,artist_name,album_id,album_name,song_duration
0,2452301661,Westlife-全专辑-按发行顺序,1403713759,Hello My Love,[45839],Westlife,83392596,Spectrum,216
1,2452301661,Westlife-全专辑-按发行顺序,1403713760,Better Man,[45839],Westlife,83392596,Spectrum,197
2,7012631,G-Dragon,26155091,미치GO - (疯狂GO),[123577],G-Dragon,2400506,미치GO,210
3,7012631,G-Dragon,28606338,Gmarket Song,[123577],G-Dragon,2857067,Gmarket Song,166
4,7012631,G-Dragon,28029459,WHO YOU? -JPN-,[123577],G-Dragon,2716078,COUP D'ETAT [+ ONE OF A KIND &amp; HEARTBREAKER],203
...,...,...,...,...,...,...,...,...,...
7512,592529745,许嵩全部歌曲,1842802179,超市,[5771],许嵩,126996669,呼吸之野,259
7513,592529745,许嵩全部歌曲,1842802095,万古,[5771],许嵩,126996669,呼吸之野,314
7514,592529745,许嵩全部歌曲,1842801513,三尺,[5771],许嵩,126996669,呼吸之野,228
7515,592529745,许嵩全部歌曲,1397105439,雨幕 - (新天龙八部端游主题曲),[5771],许嵩,82435664,雨幕 (新天龙八部端游主题曲）,240
7516,592529745,许嵩全部歌曲,1327456179,绝代风华 - (天下3十周年主题曲),[5771],许嵩,74519732,绝代风华,255

In [4]:
pysqldf = lambda query: sqldf(query, globals())

In [5]:
q11 = """select distinct cloud.album_id as album_id1, kuwo.album_id as album_id2
from cloud,kuwo
where cloud.album_name = kuwo.album_name"""

In [6]:
r11 = pysqldf(q11)
r11

      album_id1  album_id2
0      36784288    2183985
1        512710      14036
2          6874      74898
3      34708338     557333
4      35696419    3665851
...         ...        ...
1021      15595        773
1022   34428014      14100
1023      37181       2893
1024    3093007     442065
1025    2077319     112283

[1026 rows x 2 columns]

In [7]:
filter_artist =['伍佰 &amp; China Blue','七叔-叶泽浩','丫蛋蛋','丫蛋蛋/沈虫虫']
filter_list = []
for id1,id2 in r11.values.tolist():
    a1 =  cloud.loc[cloud.album_id == id1].iloc[0]
    a2 =  kuwo.loc[kuwo.album_id == id2].iloc[0]
    if a1.artist_name != a2.artist_name and not (a1.artist_name in a2.artist_name or a2.artist_name in a1.artist_name):
        if a1.artist_name not in filter_artist:
            print(id1,id2,a1.album_name, a2.album_name,a1.artist_name, a2.artist_name)
            filter_list.append([id1,id2])
filter_list.append([86631766,2176574])
filter_df = pd.DataFrame(filter_list)
filter_df.columns = ['album_id1', 'album_id2']

10909 10692298 罗生门 罗生门 罗志祥 蓝心羽
3142035 442820 我是歌手第三季 第4期 我是歌手第三季 第4期 胡彦斌 李荣浩
3142024 442307 我是歌手第三季 第3期 我是歌手第三季 第3期 胡彦斌 古巨基
3142067 444015 我是歌手第三季 第6期 我是歌手第三季 第6期 胡彦斌 谭维维
3142050 443389 我是歌手第三季 第5期 我是歌手第三季 第5期 胡彦斌 李健
3142053 446927 我是歌手第三季 第12期 我是歌手第三季 第12期 胡彦斌 谭维维
3142053 2413293 我是歌手第三季 第12期 我是歌手第三季 第12期 胡彦斌 李荣浩
93427116 15431527 上一首情歌 (国语精选) 上一首情歌 (国语精选) 林俊杰 袁娅维TIA RAY
93426151 15431527 上一首情歌 (国语精选) 上一首情歌 (国语精选) 林俊杰 袁娅维TIA RAY
93848999 14048970 达拉崩吧 达拉崩吧 黄龄 饭思思
34608091 549464 我是歌手第四季 歌王之战 我是歌手第四季 歌王之战 老狼 叶蒨文/李克勤/林子祥
34608091 2188535 我是歌手第四季 歌王之战 我是歌手第四季 歌王之战 老狼 李克勤
74715426 15513577 起风了 起风了 买辣椒也用券 周深
36067044 22261702 第三人称 第三人称 买辣椒也用券 于文文
2426046 48777 天之大 天之大 毛阿敏 费玉清
27448 63807 20世纪中华歌坛名人百集珍藏版 20世纪中华歌坛名人百集珍藏版 毛阿敏 张国荣
27448 64936 20世纪中华歌坛名人百集珍藏版 20世纪中华歌坛名人百集珍藏版 毛阿敏 那英
30551 73307 萧亚轩 同名专辑 萧亚轩 同名专辑 萧亚轩 田馥甄
35266083 2152417 歌手 第8期 歌手 第8期 林忆莲 李健
35176122 2146784 歌手 第4期 歌手 第4期 林忆莲 张杰
35188207 2148236 歌手 第5期 歌手 第5期 林忆莲 张杰
35346425 2547869 歌手 第12期 歌手 第12期 林忆莲 李健
35210349 2149637 歌手 第6期 歌手 第6期 林忆莲 张杰
35292233 2153865 歌手 第9期 歌手 第9期 林忆莲 李健
35234489 2151025 歌手 第7期 歌手 第7期 林忆莲 张碧晨
2866832 426885 想唱就唱 想唱就唱 TFBOYS 大张伟
2786862 413987 我是歌手第二季 第3期 我是歌手第二季 第3期 张宇 G.E.M.邓紫棋
3142018 441795 我是歌手第三季 第2期 我是歌手第三季 第2期 胡彦斌 张靓颖
17013 64044 Reborn Reborn 谢霆锋 李克勤
29183 2541931 3 3 谭维维 水木年华
97594311 15812 我很好 我很好 刘大壮 刘若英
3142080 445325 我是歌手第三季 第9期 我是歌手第三季 第9期 张靓颖 谭维维
3142078 445048 我是歌手第三季 第8期 我是歌手第三季 第8期 张靓颖 李健
3142071 444733 我是歌手第三季 第7期 我是歌手第三季 第7期 张靓颖 李健
2785218 418042 我是歌手第二季 总决赛 我是歌手第二季 总决赛 张杰 G.E.M.邓紫棋/方大同
2786868 418038 我是歌手第二季 第9期 我是歌手第二季 第9期 张杰 G.E.M.邓紫棋
2786864 414025 我是歌手第二季 第5期 我是歌手第二季 第5期 张杰 G.E.M.邓紫棋
2786865 414073 我是歌手第二季 第6期 我是歌手第二季 第6期 张杰 G.E.M.邓紫棋
2786863 413988 我是歌手第二季 第4期 我是歌手第二季 第4期 张杰 G.E.M.邓紫棋
2786869 418041 我是歌手第二季 第10期 我是歌手第二季 第10期 张杰 G.E.M.邓紫棋
2774162 418040 我是歌手第二季 半决赛 我是歌手第二季 半决赛 张杰 G.E.M.邓紫棋
17594 21377278 不良少年 不良少年 徐良/汪苏泷 Lil Ghost小鬼
3292515 423601 Alive Alive Sia 萨顶顶
95902047 5448220 无人知晓 无人知晓 田馥甄 许巍
1923793 64816 Greatest Hits Greatest Hits Westlife 邓丽君
23074 13133997 漫步人生路 漫步人生路 邓丽君 丫蛋蛋（马启涵）
1923822 13383513 Home Home Westlife 蔡徐坤
10886 3741160 独一无二 独一无二 罗志祥 南征北战NZBZ
3087134 441270 2015湖南卫视跨年演唱会 2015湖南卫视跨年演唱会 EXO G.E.M.邓紫棋
8166 269580 天之大 天之大 费玉清 毛阿敏
511060 1869 一夜长大 一夜长大 刘若英 梁静茹
3159840 9920305 热门华语266 热门华语266 刘若英 孙燕姿/陈奕迅
30549 5228198 红蔷薇 红蔷薇 萧亚轩 张靓颖
34559338 522925 跨年演唱会2012-2013 华语篇2 跨年演唱会2012-2013 华语篇2 王力宏 林宥嘉
34559338 2164449 跨年演唱会2012-2013 华语篇2 跨年演唱会2012-2013 华语篇2 王力宏 林宥嘉
34559296 523791 2005年TVB8金曲榜颁奖典礼 2005年TVB8金曲榜颁奖典礼 王力宏 孙燕姿
2956076 6802977 喜欢你 喜欢你 G.E.M.邓紫棋 TFBOYS
2920045 3758872 穿越火线 穿越火线 谢霆锋 G.E.M.邓紫棋
28609 76614 台北小巨蛋音乐会 台北小巨蛋音乐会 宋祖英 周杰伦
35326589 2540941 歌手 第11期 歌手 第11期 张碧晨 李健
72797621 7032661 中国新说唱 第8期 中国新说唱 第8期 艾热 AIR G.E.M.邓紫棋/ICE/潘玮柏/艾热
72603642 6892006 中国新说唱 第7期 中国新说唱 第7期 王以太 JelloRio李佳隆/艾热
72794867 7105685 中国新说唱 第9期 中国新说唱 第9期 王以太 刘柏辛Lexie
78953794 9827762 我是唱作人 第2期 我是唱作人 第2期 汪苏泷 毛不易
92561546 7225793 成全 成全 买辣椒也用券 林宥嘉
2685023 7287796 终于等到你 终于等到你 张靓颖 张信哲
3103098 541399 燕归巢 燕归巢 张杰/张靓颖 许嵩
31528 1062 祝福 祝福 叶蒨文 张学友
3308603 2188139 倩女幽魂 电影原声带 倩女幽魂 电影原声带 叶蒨文 张国荣
37313151 6036832 最美的期待 最美的期待 周笔畅 南征北战NZBZ
35663210 3668064 电影《闪光少女》OST概念音乐计划 电影《闪光少女》OST概念音乐计划 周笔畅 逃跑计划
3056858 435308 匆匆那年 匆匆那年 周深 王菲
2786861 413986 我是歌手第二季 第2期 我是歌手第二季 第2期 张宇 G.E.M.邓紫棋
2786866 418039 我是歌手第二季 第7期 我是歌手第二季 第7期 张宇 G.E.M.邓紫棋
2786867 418037 我是歌手第二季 第8期 我是歌手第二季 第8期 张宇 G.E.M.邓紫棋
3317503 518028 夏洛特烦恼 电影原声带 夏洛特烦恼 电影原声带 那英 杨宗纬
3142079 446414 我是歌手第三季 第11期 我是歌手第三季 第11期 李健 孙楠
2396284 269048 我是歌手第一季 第12期 我是歌手第一季 第12期 杨宗纬 羽·泉
34678769 6421 再见 再见 G.E.M.邓紫棋 张震岳
34678769 23811076 再见 再见 G.E.M.邓紫棋 于文文
34555303 6734740 坚强的背后 坚强的背后 胡夏 林宥嘉
37200 63001 女生宿舍 女生宿舍 田馥甄 S.H.E
17065 113810 Believe Believe 谢霆锋 Justin Bieber
2365002 268478 我是歌手第一季 第10期 我是歌手第一季 第10期 羽·泉 彭佳慧
34552 14281 星光同学会 星光同学会 杨宗纬 林宥嘉
2902015 274663 摘金宝典 摘金宝典 齐秦 黎明
37169 5460 奇幻乐园演唱会 奇幻乐园演唱会 田馥甄 S.H.E
489825 14858 斗牛，要不要 电视原声带 斗牛，要不要 电视原声带 田馥甄 S.H.E
84310200 13156 My Way My Way 张碧晨 张敬轩
2379124 10692298 罗生门 罗生门 罗志祥 蓝心羽
3003027 11439151 重生 重生 丁于/姚贝娜 蔡徐坤
71612860 5323895 最美的期待 最美的期待 南征北战NZBZ 周笔畅
35067010 10450707 闪耀 闪耀 南征北战NZBZ 汪苏泷
25394 661 丝路 丝路 梁静茹 齐秦
512075 539871 K情歌2 K情歌2 蔡依林 蔡健雅
3076565 3938576 热门华语253 热门华语253 林俊杰 吴青峰
2290034 266854 我是歌手第一季 第5期 我是歌手第一季 第5期 尚雯婕 林志炫
2298011 267201 我是歌手第一季 第6期 我是歌手第一季 第6期 尚雯婕 羽·泉
2302089 267529 我是歌手第一季 第7期 我是歌手第一季 第7期 尚雯婕 羽·泉
2353004 268117 我是歌手第一季 第9期 我是歌手第一季 第9期 尚雯婕 羽·泉
2415003 269385 我是歌手第一季 总决赛 我是歌手第一季 总决赛 齐秦/齐豫 羽·泉
37029433 5267934 心里学 心里学 徐佳莹 周杰伦
34943943 1361073 梦幻诛仙 梦幻诛仙 张碧晨 汪苏泷
133972048 25348821 余烬 余烬 吉克隽逸 杨千嬅
28586 5471229 我的骄傲 我的骄傲 容祖儿 林志颖
37542551 2162826 爱的主题歌 爱的主题歌 潘玮柏 信乐团
18929 7358 从开始到现在 从开始到现在 张信哲 张震岳
81942896 10796060 限定的记忆 限定的记忆 Lil Ghost小鬼 蔡徐坤
3109627 3913412 热门华语262 热门华语262 姚贝娜 方大同/薛凯琪
2759696 414257 伍乐城 幻想集 伍乐城 幻想集 古天乐 陈伟霆
34961173 3992519 让我留在你身边 让我留在你身边 陈奕迅 鹿晗
17117 16363 神雕侠侣 电视主题曲原声大戏 神雕侠侣 电视主题曲原声大戏 梁静茹 张靓颖
37577228 507913 2GETHER 4EVER ENCORE 演唱会影音馆 2GETHER 4EVER ENCORE 演唱会影音馆 S.H.E/五月天 S.H.E/动力火车
2286009 4168738 齐天周大圣之西游双记 电影歌乐游唱版 齐天周大圣之西游双记 电影歌乐游唱版 卢冠廷/莫文蔚 梅艳芳
86832916 5323895 最美的期待 最美的期待 南征北战NZBZ 周笔畅
71724250 6330922 中国新说唱 第1期 中国新说唱 第1期 那吾克热-NW 刘柏辛Lexie
73471009 7227492 中国新说唱 第12期 中国新说唱 第12期 王以太 MC HotDog 热狗/张震岳
73471009 7229321 中国新说唱 第12期 中国新说唱 第12期 王以太 G.E.M.邓紫棋
18881 23811076 再见 再见 张震岳 于文文
81105928 10436872 画 画 饭思思 花僮
81107341 12033994 芒种 芒种 饭思思 腾格尔
35886087 427508 穿越火线 穿越火线 G.E.M.邓紫棋 谢霆锋
36875478 431418 重生 重生 容祖儿 丁于
36875478 11439151 重生 重生 容祖儿 蔡徐坤
71852934 6468862 中国新说唱 第2期 中国新说唱 第2期 王以太 满舒克
75602739 9138549 2019年中央广播电视总台元宵晚会 2019年中央广播电视总台元宵晚会 张艺兴 易烊千玺/王俊凯/王源
15428 3741160 独一无二 独一无二 谭咏麟/陈慧娴 南征北战NZBZ
78321975 7528033 黑白 黑白 Lil Ghost小鬼 花僮
25554 1383 呼吸 呼吸 林忆莲 蔡健雅
2901199 426592 我最喜爱的Eric Kwok作品展 我最喜爱的Eric Kwok作品展 林忆莲 陈奕迅
10322 18002607 一个人 一个人 姜育恒 王嘉尔
18966 63899 如燕盘旋而来的思念 如燕盘旋而来的思念 张雨生 林志颖
510762 75956 K情歌9 K情歌9 张靓颖/王力宏 信
74358918 538046 长腿叔叔 长腿叔叔 花僮 袁娅维TIA RAY
83351855 431418 重生 重生 蔡徐坤 丁于
75116936 7069971 起风了 起风了 吴青峰 买辣椒也用券
75116936 15513577 起风了 起风了 吴青峰 周深
511483 36870 国语经典101 国语经典101 齐秦 黎明
94765283 7069971 起风了 起风了 周深 买辣椒也用券
19016 7900704 说谎 说谎 张信哲 花僮
3087124 2163025 2015浙江卫视跨年演唱会 2015浙江卫视跨年演唱会 丁当 方大同
127048701 20276678 为歌而赞 第9期 为歌而赞 第9期 于文文 孙楠
14234 4124845 丝路 丝路 齐秦 梁静茹
29771 66961 胡思乱想 胡思乱想 王菲 无印良品
3139962 5519719 我变了 我没变 我变了 我没变 杨宗纬 张碧晨
27849 63807 20世纪中华歌坛名人百集珍藏版 20世纪中华歌坛名人百集珍藏版 那英 张国荣
37251604 17505614 无所畏惧 无所畏惧 袁娅维TIA RAY 周深
2263157 13822011 改变自己 改变自己 王力宏 于文文
2569273 4974593 唯一 唯一 王力宏 满舒克
3101004 64821 甜蜜蜜 甜蜜蜜 鹿晗 邓丽君
3101004 511160 甜蜜蜜 甜蜜蜜 鹿晗 邓丽君
35384255 548002 I Believe I Believe 张靓颖 张信哲
35368354 18187151 寻 寻 华晨宇 郁可唯
39723555 7298455 只要平凡 只要平凡 张杰/张碧晨 花僮
126409089 19971774 为歌而赞 第7期 为歌而赞 第7期 周笔畅 袁娅维TIA RAY
34614371 435308 匆匆那年 匆匆那年 双笙（陈元汐） 王菲
28692 63807 20世纪中华歌坛名人百集珍藏版 20世纪中华歌坛名人百集珍藏版 宋祖英 张国荣
28692 64936 20世纪中华歌坛名人百集珍藏版 20世纪中华歌坛名人百集珍藏版 宋祖英 那英
3001333 9560 为爱而生 为爱而生 宋祖英 五月天
34428014 14100 2006 MP3人气超强总冠军 2006 MP3人气超强总冠军 王力宏 罗志祥

In [8]:
filter_df

     album_id1  album_id2
0        10909   10692298
1      3142035     442820
2      3142024     442307
3      3142067     444015
4      3142050     443389
..         ...        ...
156      28692      63807
157      28692      64936
158    3001333       9560
159   34428014      14100
160   86631766    2176574

[161 rows x 2 columns]

In [9]:
q12 = """select r11.*
from r11
where (r11.album_id1, r11.album_id2) not in (select * from filter_df)"""

In [10]:
same_album = pysqldf(q12)
same_album.to_csv("same_entity_pair/same_album",header = False,index=False, sep='\t')
same_album

     album_id1  album_id2
0     36784288    2183985
1       512710      14036
2         6874      74898
3     34708338     557333
4     35696419    3665851
..         ...        ...
860     489704     320266
861      15595        773
862      37181       2893
863    3093007     442065
864    2077319     112283

[865 rows x 2 columns]

In [11]:
q2 = """
select distinct cloud.song_name, cloud.song_id, kuwo.song_id,cloud.artist_name,kuwo.artist_name
from cloud,kuwo
where cloud.song_name = kuwo.song_name 
and abs(cloud.song_duration - kuwo.song_duration) < 5 
and cloud.album_name = kuwo.album_name
and cloud.artist_name != kuwo.artist_name"""

In [12]:
r2 = pysqldf(q2)
r2

,song_name,song_id,song_id,artist_name,artist_name
0,每一次想你,255544,165188,李玟,CoCo李玟
1,颜色,255483,3208936,李玟,CoCo李玟
2,月牙湾,1338414110,61499912,丫蛋蛋/沈虫虫,丫蛋蛋（马启涵）/沈虫虫
3,漫步人生路,229285,91967691,邓丽君,丫蛋蛋（马启涵）
4,变成回忆,33991037,23643122,本兮,单色凌/本兮
5,匆匆那年,29759371,5844591,周深,王菲
6,一念之间,1378203023,6486070,张杰,张杰/莫文蔚
7,不一样的精彩,29307177,5352969,丁于/姚贝娜,丁于
8,伤心地铁,385537,40170984,光良,无印良品
9,恍然大悟,385551,59385,品冠,无印良品
10,叩叩,26390167,17899688,李玟,CoCo李玟
11,你的微笑,354601,91622,F.I.R.,F.I.R.飞儿乐团
12,雨樱花,354390,6832491,F.I.R.,F.I.R.飞儿乐团
13,眷恋,354409,6832497,F.I.R.,F.I.R.飞儿乐团
14,Hot Party,1312695489,41390397,刘雨昕XIN,刘雨昕
15,FEEL GOOD,1312703419,40829000,刘雨昕XIN,刘雨昕
16,不潮不用花钱,108463,442549,By2/林俊杰,林俊杰
17,年岁,1877042785,147972105,七叔-叶泽浩,七叔（叶泽浩）
18,On The Ground,1827038716,169745088,ROSÉ,ROSÉ (로제)
19,牵挂,157342,60251,伍佰 &amp; China Blue,伍佰 And China Blue
20,与你到永久,157101,28718451,伍佰 &amp; China Blue,伍佰 And China Blue
21,Last Dance,157276,315892,伍佰 &amp; China Blue,伍佰 And China Blue
22,白鸽,157092,28718450,伍佰 &amp; China Blue,伍佰 And China Blue
23,踏山河,1804320463,156483846,七叔-叶泽浩,七叔（叶泽浩）
24,星辰大海,1817702136,165563101,七叔-叶泽浩,七叔（叶泽浩）
25,客子光阴,1806127843,159927464,七叔-叶泽浩,七叔（叶泽浩）
26,白发,1451692311,91885612,七叔-叶泽浩,七叔（叶泽浩）
27,送明月,1844681373,177487668,七叔-叶泽浩,七叔（叶泽浩）
28,雨下,1451699772,84314630,七叔-叶泽浩,七叔（叶泽浩）
29,一个人的时钟,1451689758,82241382,七叔-叶泽浩,七叔（叶泽浩）
30,生长,1451692415,85794398,七叔-叶泽浩,七叔（叶泽浩）
31,长腿叔叔,1324890556,6837617,花僮,袁娅维TIA RAY
32,谜底,555770479,41386305,洛天依/花僮,花僮
33,梦醒时分,156284,1086935,伍佰 &amp; China Blue,伍佰 And China Blue
34,I Believe,472854294,7000561,张靓颖,张信哲

In [13]:
same_song_appendix = [[255544,165188],
[1338414110,61499912],
[26390167,17899688],
[354601,91622],
[354390,6832491],
[354409,6832497],
[1312695489,41390397],
[1312703419,40829000],
[1827038716,169745088],
[157342,60251],
[157101,28718451],
[157276,315892],
[157092,28718450],
[1877042785,147972105],
[1804320463,156483846],
[1817702136,165563101],
[1806127843,159927464],
[1451692311,91885612],
[1844681373,177487668],
[1451699772,84314630],
[1451689758,82241382],
[1451692415,85794398]]

In [14]:
q3 = """
select distinct cloud.song_id as song_id1, kuwo.song_id as song_id2
from cloud,kuwo
where cloud.song_name = kuwo.song_name 
and abs(cloud.song_duration - kuwo.song_duration) < 5 
and cloud.album_name = kuwo.album_name
and cloud.artist_name = kuwo.artist_name"""

In [15]:
r3 = pysqldf(q3)
r3

       song_id1   song_id2
0     518863916   22867593
1      32737496    6482330
2     399354629   11594987
3         70852     530755
4     473441510   23674858
..          ...        ...
774   411214279    7056885
775      167876     455880
776   412902950    7095221
777    30064004    6213991
778  1842784921  176715653

[779 rows x 2 columns]

In [16]:
q4= """
select distinct cloud.song_name as song_name1,kuwo.song_name as song_name2,cloud.song_id as song_id1, kuwo.song_id as song_id2
from cloud,kuwo
where cloud.song_name != kuwo.song_name 
and abs(cloud.song_duration - kuwo.song_duration) < 5
and cloud.album_name = kuwo.album_name
and cloud.artist_name = kuwo.artist_name
and cloud.song_name like '%-%'"""

In [17]:
r4= pysqldf(q4)
li = []
for i in range(r4.shape[0]):
    if r4.iloc[i].song_name2 in r4.iloc[i].song_name1:
        li.append([r4.iloc[i].song_id1,r4.iloc[i].song_id2])
r4 = pd.DataFrame(li)
r4.columns = ['song_id1', 'song_id2']
r4

       song_id1  song_id2
0     414002848   7140851
1     488256625  26364884
2      16435064  79200580
3      35447132   6660024
4        165340   1244660
..          ...       ...
177  1338638320  62194752
178  1375657748  71772030
179      108118    990108
180      354549    350635
181   512358200  30350752

[182 rows x 2 columns]

In [18]:
q5= """
select distinct cloud.song_name,kuwo.song_name, cloud.song_id, kuwo.song_id,cloud.artist_name,kuwo.artist_name
from cloud,kuwo
where cloud.song_name != kuwo.song_name 
and abs(cloud.song_duration - kuwo.song_duration) < 5
and cloud.album_name = kuwo.album_name
and cloud.artist_name != kuwo.artist_name
and cloud.song_name like '%-%'"""

In [19]:
r5= pysqldf(q5)
r5

,song_name,song_name,song_id,song_id,artist_name,artist_name
0,相思(电视剧《西游记后传》片尾曲) - (电视剧《西游记后传》片尾曲),一剪梅,26217337,1075986,毛阿敏,费玉清
1,崇拜 (live) - (原唱：梁静茹),你就不要想起我(Live),464647428,22399766,林忆莲,张杰
2,离歌 (Live) - (原唱：信乐团),Don’t Break My Heart(Live),31877250,6248651,张靓颖,胡彦斌
3,离歌 (Live) - (原唱：信乐团),贝加尔湖畔(Live),31877250,6248654,张靓颖,李健
4,Black Or White - (原唱：Michael Jackson),掌心(Live),28427750,4001245,张杰,品冠
5,听你听我 - (原唱：张惠妹),我要我们在一起(Live),28427742,3984263,张杰,G.E.M.邓紫棋
6,花房姑娘 - (原唱：崔健),当(Live),28427777,14656359,韩磊,动力火车
7,漫步人生路 (原唱：邓丽君) - (电影《大赢家》片尾曲),漫步人生路,1432160163,91967691,丫蛋蛋,丫蛋蛋（马启涵）
8,不要来找我 - (原唱：杨乃文),黑色柳丁(Live),28427766,4404394,张宇,周笔畅
9,袖手旁观 (Live) - (原唱：齐秦),突然想爱你(Live),31877484,6290363,李健,孙楠
10,灼羽 - (手游《倩女幽魂》主题曲),灼羽 (人声版),1414783134,86091198,丫蛋蛋,丫蛋蛋（马启涵）
11,Before I Fall In Love - (电影《落跑新娘》插曲),Before I Fall in Love(Album Version),255227,59310038,李玟,CoCo李玟
12,说爱你 - (电影《空中拜金女》中文主题曲),记念,5255441,7024494,蔡依林,蔡健雅
13,梦幻诛仙 - (手游《梦幻诛仙》同名主题曲),梦幻诛仙,438456232,9934211,张碧晨,汪苏泷
14,手心的蔷薇 - (Beautiful),新地球,29848657,6125731,G.E.M.邓紫棋/林俊杰,林俊杰
15,世上哪有树缠藤 - (音乐剧《刘三姐》选段),日月凌空,29343673,1220700,姚贝娜/沙宝亮,姚贝娜
16,不为谁而作的歌 (Live) - (原唱 : 林俊杰),天空之城(Live),409060875,7024392,徐佳莹/林俊杰,张信哲
17,不为谁而作的歌 (Live) - (原唱 : 林俊杰),王妃(Live),409060875,7024394,徐佳莹/林俊杰,黄致列
18,月光爱人 - (原唱 : 李玟),爱是永恒(Live),409302034,7024393,李玟,李克勤
19,月光爱人 - (原唱 : 李玟),突然好想你(Live),409302034,7024395,李玟,徐佳莹
20,月光爱人 - (原唱 : 李玟),月光爱人(Live),409302034,7024396,李玟,CoCo李玟
21,起风了 - (电视剧《加油，你是最棒的》主题曲),起风了,1338695683,149121488,吴青峰,周深
22,挪威的森林 - (Norwegian Forest),挪威的森林,157288,888898,伍佰 &amp; China Blue,伍佰 And China Blue
23,放逐之刃 - (《英雄联盟》瑞文同人主题曲),放逐之刃,511656187,41389348,花僮,洛天依/花僮
24,当 (Live) - (电视剧《两个天堂之还珠格格》片头曲),花房姑娘(Live),28427776,4404401,动力火车,韩磊
25,北京北京 - (原唱：汪峰),管他什么音乐(Live),28427785,4404412,韩磊,周笔畅
26,甜蜜蜜 - (电影《甜蜜蜜》同名主题曲),你在我梦里,30482048,838090,鹿晗,邓丽君
27,天下没有不散的宴席 (Live) - (原唱：郑钧),Easy Lover(Live),26184006,3325231,周晓鸥/谭维维,林志炫/萧敬腾
28,只要平凡 - (电影《我不是药神》主题曲),只要平凡,574919767,55495902,张杰/张碧晨,花僮
29,新窝 - (电视剧《公主小妹》主题曲),明日香,354549,350631,S.H.E/飞轮海,飞轮海
30,突然好想你 (Live) - (原唱：五月天),爱是永恒(Live),409060879,7024393,徐佳莹,李克勤
31,突然好想你 (Live) - (原唱：五月天),月光爱人(Live),409060879,7024396,徐佳莹,CoCo李玟

In [20]:
same_song_appendix.extend([[1432160163,91967691],
[1414783134,86091198],                   
[157288,888898],
[511656187,41389348]
])

In [21]:
same_song_appendix = pd.DataFrame(same_song_appendix)
same_song_appendix.columns = ['song_id1', 'song_id2']
same_song_appendix

      song_id1   song_id2
0       255544     165188
1   1338414110   61499912
2     26390167   17899688
3       354601      91622
4       354390    6832491
5       354409    6832497
6   1312695489   41390397
7   1312703419   40829000
8   1827038716  169745088
9       157342      60251
10      157101   28718451
11      157276     315892
12      157092   28718450
13  1877042785  147972105
14  1804320463  156483846
15  1817702136  165563101
16  1806127843  159927464
17  1451692311   91885612
18  1844681373  177487668
19  1451699772   84314630
20  1451689758   82241382
21  1451692415   85794398
22  1432160163   91967691
23  1414783134   86091198
24      157288     888898
25   511656187   41389348

In [22]:
same_song = pd.concat([r3,r4,pd.DataFrame(same_song_appendix)]).drop_duplicates()
same_song.sort_values('song_id1',inplace=True)
same_song
same_song.to_csv("same_entity_pair/same_song",header = False,index=False, sep='\t')

       song_id1   song_id2
614       59914     658490
438       59917     658492
437       59968     352586
376       60208   38949976
375       60238     238200
..          ...        ...
17   1920941709  210040970
141  1922623139  210656825
738  1925396986  212177214
510  1927438231  213005767
110  1929346993  213755490

[987 rows x 2 columns]

In [23]:
same_artist = pd.read_csv("same_entity_pair/same_artist",header = None,delimiter='\t')
same_artist.columns = ['cloud_artist_id', 'kuwo_artist_id']
same_artist

     cloud_artist_id  kuwo_artist_id
0              45839             382
1             123577           10582
2               3699             490
3               7200            9924
4               5929            5304
..               ...             ...
228            37995           21525
229         12049183          226833
230         12479356          661412
231             5769             161
232         31002807         4355654

[233 rows x 2 columns]

In [24]:
ent_links = pd.DataFrame(np.concatenate([df.values for df in [same_artist,same_album,same_song]]))
ent_links.to_csv("same_entity_pair/ent_links",header = False,index=False, sep='\t')

In [25]:
same_artist.values

array([[   45839,      382],
       [  123577,    10582],
       [    3699,      490],
       [    7200,     9924],
       [    5929,     5304],
       [   11127,  2533015],
       [  188558,   116675],
       [  188565,   117806],
       [    2164,     8925],
       [    7570,     1328],
       [ 1050282,   251015],
       [   38853,      752],
       [    3694,      721],
       [   46487,     1627],
       [   44266,     4968],
       [    3683,     1094],
       [    4895,      973],
       [    3066,     1434],
       [ 1038093,   116087],
       [   35531,     5317],
       [    7652,      891],
       [    3273,     5361],
       [   11097,     1715],
       [    5538,     5357],
       [    2747,      395],
       [ 1211046,   126144],
       [12079219,  2537531],
       [    7219,      978],
       [    5346,     1416],
       [    8326,     1431],
       [  126339,      125],
       [12382970,  1486611],
       [    3684,     1062],
       [    2517,      683],
       [    3704,      862],
       [    5770,   201215],
       [    9102,      389],
       [   11562,    68432],
       [   11363,      312],
       [  816248,   118640],
       [    7890,     1509],
       [    5205,      810],
       [    9270,     1042],
       [   13193,      354],
       [    9061,      868],
       [    3682,     1256],
       [    2852,      448],
       [12085562,   784431],
       [    6469,     1209],
       [    8921,     1213],
       [    3072,     1405],
       [    9945,      226],
       [    5768,     1768],
       [    8331,      142],
       [  861777,   125910],
       [    8336,     1014],
       [    9951,      621],
       [30207301,  3161078],
       [    2524,     5334],
       [    4723,      314],
       [    5196,      451],
       [  827728,   128294],
       [  999220,   123557],
       [   10562,      492],
       [    7225,      233],
       [  865007,  1485176],
       [    8918,     1127],
       [    6460,      896],
       [    9178,     5349],
       [ 1198123,  3189656],
       [    6472,      680],
       [    5771,     1887],
       [   10209,       36],
       [ 1030001,   195793],
       [    7763,     5371],
       [   10200,     5260],
       [    4941,       80],
       [    4130,     3913],
       [46995893,  3122506],
       [12275389,   289978],
       [   10695,       26],
       [    5773,     1072],
       [    9278,      770],
       [    9489,      531],
       [ 1083118,   695036],
       [ 1024308,   195792],
       [12236125,   345656],
       [12867228,  3653874],
       [31165848,  3422934],
       [    7534,     1649],
       [   10561,      211],
       [   10204,     1367],
       [    9272,      744],
       [12025552,   260851],
       [  187295,   116677],
       [  159300,    74016],
       [ 1199064,   760069],
       [13899303,  1516976],
       [12357157,   888689],
       [   74625,     8615],
       [   31211,      151],
       [   10558,     1115],
       [    4721,     1504],
       [    9943,       66],
       [    5247,     1711],
       [    9548,     5359],
       [   11561,     1596],
       [   13283,     1170],
       [    5347,     1200],
       [12068017,   374042],
       [    6457,      833],
       [    2738,      983],
       [  759509,    70246],
       [   11761,     8415],
       [    6456,      332],
       [    3691,      286],
       [   13190,      548],
       [    2842,      357],
       [    2118,     1172],
       [   12977,     4450],
       [    3695,     1351],
       [    6453,       96],
       [  956206,    66258],
       [    5200,      443],
       [    8325,      317],
       [    8926,      909],
       [    8329,      565],
       [  956386,   185500],
       [  939088,   192913],
       [    2116,       47],
       [    9269,      249],
       [ 1203045,   225366],
       [12047978,   288672],
       [    3706,      646],
       [    9940,     4536],
       [ 1045123,   257187],
       [   10559,     1001],
       [   11564,      419],
       [    3686,     1234],
       [    6462,      729],
       [   12709,      624],
       [    3701,      858],
       [13972109,   265748],
       [    6066,     5265],
       [12121264,  2473202],
       [    7214,      522],
       [   13418,       25],
       [12138269,  1456705],
       [12157298,  3247267],
       [12420149,   313587],
       [    5781,      947],
       [    9621,      385],
       [  166018,   110631],
       [    4479,      582],
       [    3685,     5214],
       [    4813,     1383],
       [    9167,     1574],
       [13058503,  2723835],
       [    6452,      336],
       [   12712,      436],
       [    7891,     1332],
       [    2849,      720],
       [12493781,  1479745],
       [    2545,     4310],
       [    4942,     2866],
       [    2112,     1359],
       [    4292,    61144],
       [    4755,      892],
       [  189873,   111900],
       [    8327,      801],
       [    9606,     1306],
       [ 1142042,   271275],
       [12065096,  3908333],
       [    5198,     1571],
       [ 1156455,   120383],
       [    9276,     1275],
       [  188141,   814518],
       [    3064,     1020],
       [    3692,      925],
       [   10577,     1178],
       [   10473,    32584],
       [    1876,      922],
       [    6454,     1493],
       [    6731,    89199],
       [    2124,     1607],
       [    2844,      658],
       [    6491,      627],
       [13056440,  2522330],
       [12217134,  1312347],
       [  187229,    63220],
       [    3456,     1600],
       [  906118,   116089],
       [  222871,      210],
       [    3697,      690],
       [12514278,  1494307],
       [    9615,     1717],
       [    5068,    10221],
       [ 1124151,   290230],
       [34199696,  1624596],
       [    9944,     1536],
       [12062255,  2718319],
       [    5354,   195702],
       [13145283,  2880144],
       [    8281,    72182],
       [ 1143033,  1035147],
       [    6459,     1074],
       [    7235,      871],
       [ 1019154,   223504],
       [    3073,       77],
       [ 1047015,   123672],
       [   92526,     9718],
       [ 1007170,   224764],
       [ 1026069,   137232],
       [ 1087387,    40580],
       [    7768,      527],
       [    9952,     1569],
       [   10367,     5303],
       [51002965,   908596],
       [  275494,   119388],
       [    2843,     1610],
       [    7647,     3449],
       [    7224,     1501],
       [29802127,  2724951],
       [   12413,   136340],
       [    8330,     1580],
       [    6719,     8619],
       [   10571,      307],
       [   43033,     1107],
       [   37995,    21525],
       [12049183,   226833],
       [12479356,   661412],
       [    5769,      161],
       [31002807,  4355654]], dtype=int64)